package executor

import (
	"bytes"
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ethpandaops/benchmarkoor/pkg/config"
	"github.com/sirupsen/logrus"
	"gopkg.in/yaml.v3"
)

// TempoSuiteFormat is the versioned interchange format understood by the
// Benchmarkoor Tempo source and emitted by Tempo's suite generator.
const TempoSuiteFormat = "tempo-engine-suite/v1"

// TempoSuiteOrigin makes generated data reproducible and ties imported EEST
// cases or Tempo-native workloads back to the tool and revision that made them.
type TempoSuiteOrigin struct {
	Kind       string `yaml:"kind,omitempty" json:"kind,omitempty"`
	Repository string `yaml:"repository,omitempty" json:"repository,omitempty"`
	Revision   string `yaml:"revision,omitempty" json:"revision,omitempty"`
	Generator  string `yaml:"generator,omitempty" json:"generator,omitempty"`
	Version    string `yaml:"version,omitempty" json:"version,omitempty"`
	Seed       string `yaml:"seed,omitempty" json:"seed,omitempty"`
}

// TempoSuiteChain identifies the chain configuration required to replay a
// suite. Genesis is resolved relative to the manifest.
type TempoSuiteChain struct {
	Name     string `yaml:"name,omitempty" json:"name,omitempty"`
	ChainID  uint64 `yaml:"chain_id,omitempty" json:"chain_id,omitempty"`
	Hardfork string `yaml:"hardfork,omitempty" json:"hardfork,omitempty"`
	Genesis  string `yaml:"genesis" json:"genesis"`
}

// TempoSuiteManifest is the semantic benchmark interchange format. A suite can
// contain Ethereum-compatibility cases imported from Benchmarkoor/EEST and
// Tempo-specific cases generated by Tempo while using one execution/reporting
// path.
type TempoSuiteManifest struct {
	Format      string                   `yaml:"format"`
	Name        string                   `yaml:"name"`
	Description string                   `yaml:"description,omitempty"`
	Origin      TempoSuiteOrigin         `yaml:"origin,omitempty"`
	Chain       TempoSuiteChain          `yaml:"chain"`
	Metadata    map[string]string        `yaml:"metadata,omitempty"`
	Defaults    TempoSuiteDefaults       `yaml:"defaults,omitempty"`
	PreRun      []TempoSuiteCall         `yaml:"pre_run,omitempty"`
	Tests       []TempoSuiteTestManifest `yaml:"tests"`
}

// TempoSuiteDefaults are inherited by reth_newPayload calls that do not set an
// explicit value.
type TempoSuiteDefaults struct {
	WaitForPersistence *bool  `yaml:"wait_for_persistence,omitempty"`
	WaitForCaches      *bool  `yaml:"wait_for_caches,omitempty"`
	ExpectedStatus     string `yaml:"expected_status,omitempty"`
}

// TempoSuiteTestManifest describes the setup/measurement/cleanup phases of a
// single isolated benchmark case.
type TempoSuiteTestManifest struct {
	Name        string            `yaml:"name"`
	Description string            `yaml:"description,omitempty"`
	Tags        []string          `yaml:"tags,omitempty"`
	Metadata    map[string]string `yaml:"metadata,omitempty"`
	Setup       []TempoSuiteCall  `yaml:"setup,omitempty"`
	Test        []TempoSuiteCall  `yaml:"test"`
	Cleanup     []TempoSuiteCall  `yaml:"cleanup,omitempty"`
}

// TempoSuiteCall is either a raw-RLP reth_newPayload request or an explicit
// JSON-RPC method/params pair. The latter keeps the format extensible and is
// used for reth_forkchoiceUpdated calls.
type TempoSuiteCall struct {
	Method                  string  `yaml:"method,omitempty"`
	Params                  []any   `yaml:"params,omitempty"`
	RLP                     string  `yaml:"rlp,omitempty"`
	RLPFile                 string  `yaml:"rlp_file,omitempty"`
	BAL                     string  `yaml:"bal,omitempty"`
	BALFile                 string  `yaml:"bal_file,omitempty"`
	WaitForPersistence      *bool   `yaml:"wait_for_persistence,omitempty"`
	WaitForCaches           *bool   `yaml:"wait_for_caches,omitempty"`
	BlockNumber             *uint64 `yaml:"block_number,omitempty"`
	BlockHash               string  `yaml:"block_hash,omitempty"`
	GasUsed                 *uint64 `yaml:"gas_used,omitempty"`
	TransactionCount        *uint64 `yaml:"transaction_count,omitempty"`
	ExpectedStatus          string  `yaml:"expected_status,omitempty"`
	ValidationErrorContains string  `yaml:"validation_error_contains,omitempty"`
	ExpectedRPCErrorCode    *int    `yaml:"expected_rpc_error_code,omitempty"`
}

type tempoSuiteSource struct {
	log          logrus.FieldLogger
	cfg          *config.TempoSuiteSource
	filter       *filterMatcher
	manifestPath string
	basePath     string
	manifestRaw  []byte
	manifest     *TempoSuiteManifest
}

// NewTempoSuiteSource creates a semantic Tempo suite source.
func NewTempoSuiteSource(
	log logrus.FieldLogger,
	cfg *config.TempoSuiteSource,
	filter *filterMatcher,
) Source {
	return &tempoSuiteSource{
		log:    log.WithField("source", "tempo_suite"),
		cfg:    cfg,
		filter: filter,
	}
}

var (
	_ Source          = (*tempoSuiteSource)(nil)
	_ GenesisProvider = (*tempoSuiteSource)(nil)
)

func (s *tempoSuiteSource) Prepare(_ context.Context) (*PreparedSource, error) {
	manifestPath, err := filepath.Abs(s.cfg.Manifest)
	if err != nil {
		return nil, fmt.Errorf("resolving manifest path: %w", err)
	}

	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("reading Tempo suite manifest: %w", err)
	}

	decoder := yaml.NewDecoder(bytes.NewReader(raw))
	decoder.KnownFields(true)

	var manifest TempoSuiteManifest
	if err := decoder.Decode(&manifest); err != nil {
		return nil, fmt.Errorf("decoding Tempo suite manifest: %w", err)
	}

	if err := validateTempoSuiteManifest(&manifest); err != nil {
		return nil, err
	}

	s.manifestPath = manifestPath
	s.basePath = filepath.Dir(manifestPath)
	s.manifestRaw = raw
	s.manifest = &manifest

	identity := append([]byte(nil), raw...)
	if manifest.Chain.Genesis != "" {
		genesis, readErr := os.ReadFile(s.resolvePath(manifest.Chain.Genesis))
		if readErr != nil {
			return nil, fmt.Errorf("reading chain.genesis: %w", readErr)
		}
		identity = appendIdentity(identity, manifest.Chain.Genesis, genesis)
	}

	preRun, referenced, err := s.buildStep("pre_run", manifest.PreRun)
	if err != nil {
		return nil, err
	}
	identity = append(identity, referenced...)

	prepared := &PreparedSource{BasePath: s.basePath, IdentityContent: identity}
	if preRun != nil {
		prepared.PreRunSteps = []*StepFile{preRun}
	}

	for _, test := range manifest.Tests {
		filterValue := strings.Join(append([]string{test.Name}, test.Tags...), " ")
		if !s.filter.match(filterValue) {
			continue
		}

		entry := &TestWithSteps{
			Name:        test.Name,
			Description: test.Description,
			Tags:        append([]string(nil), test.Tags...),
			Metadata:    cloneStringMap(test.Metadata),
		}

		entry.Setup, referenced, err = s.buildStep(test.Name+"/setup", test.Setup)
		if err != nil {
			return nil, err
		}
		prepared.IdentityContent = append(prepared.IdentityContent, referenced...)

		entry.Test, referenced, err = s.buildStep(test.Name+"/test", test.Test)
		if err != nil {
			return nil, err
		}
		prepared.IdentityContent = append(prepared.IdentityContent, referenced...)

		entry.Cleanup, referenced, err = s.buildStep(test.Name+"/cleanup", test.Cleanup)
		if err != nil {
			return nil, err
		}
		prepared.IdentityContent = append(prepared.IdentityContent, referenced...)

		prepared.Tests = append(prepared.Tests, entry)
	}

	if len(prepared.Tests) == 0 {
		return nil, fmt.Errorf("tempo suite has no tests matching filter %q", s.filter.String())
	}

	s.log.WithFields(logrus.Fields{
		"manifest": manifestPath,
		"suite":    manifest.Name,
		"tests":    len(prepared.Tests),
	}).Info("Prepared Tempo Engine suite")

	return prepared, nil
}

func validateTempoSuiteManifest(manifest *TempoSuiteManifest) error {
	if manifest.Format != TempoSuiteFormat {
		return fmt.Errorf("unsupported Tempo suite format %q, expected %q", manifest.Format, TempoSuiteFormat)
	}
	if strings.TrimSpace(manifest.Name) == "" {
		return fmt.Errorf("tempo suite name is required")
	}
	if strings.TrimSpace(manifest.Chain.Genesis) == "" {
		return fmt.Errorf("tempo suite chain.genesis is required")
	}
	if len(manifest.Tests) == 0 {
		return fmt.Errorf("tempo suite must contain at least one test")
	}

	seen := make(map[string]struct{}, len(manifest.Tests))
	for i, test := range manifest.Tests {
		if strings.TrimSpace(test.Name) == "" {
			return fmt.Errorf("tempo suite test %d has no name", i)
		}
		if _, ok := seen[test.Name]; ok {
			return fmt.Errorf("tempo suite contains duplicate test name %q", test.Name)
		}
		seen[test.Name] = struct{}{}
		if len(test.Test) == 0 {
			return fmt.Errorf("tempo suite test %q has no measured calls", test.Name)
		}
	}

	return nil
}

func (s *tempoSuiteSource) buildStep(name string, calls []TempoSuiteCall) (*StepFile, []byte, error) {
	if len(calls) == 0 {
		return nil, nil, nil
	}

	lines := make([]string, 0, len(calls))
	metadata := make([]*RequestMetadata, 0, len(calls))
	var identity []byte

	for i, call := range calls {
		line, meta, referenced, err := s.buildCall(i+1, call)
		if err != nil {
			return nil, nil, fmt.Errorf("building %s call %d: %w", name, i+1, err)
		}
		lines = append(lines, line)
		metadata = append(metadata, meta)
		identity = append(identity, referenced...)
	}

	provider := &tempoStepProvider{lines: lines, metadata: metadata}
	return &StepFile{Name: name, Provider: provider}, identity, nil
}

func (s *tempoSuiteSource) buildCall(
	id int,
	call TempoSuiteCall,
) (string, *RequestMetadata, []byte, error) {
	method := call.Method
	params := call.Params
	var identity []byte

	hasRLP := call.RLP != "" || call.RLPFile != ""
	if !hasRLP && (call.BAL != "" || call.BALFile != "") {
		return "", nil, nil, fmt.Errorf("bal/bal_file requires rlp or rlp_file")
	}
	if !hasRLP && (call.WaitForPersistence != nil || call.WaitForCaches != nil) {
		return "", nil, nil, fmt.Errorf("wait flags require rlp or rlp_file")
	}
	if hasRLP {
		if method == "" {
			method = "reth_newPayload"
		}
		if method != "reth_newPayload" {
			return "", nil, nil, fmt.Errorf("rlp/rlp_file is only valid with reth_newPayload")
		}
		if len(params) > 0 {
			return "", nil, nil, fmt.Errorf("params and rlp/rlp_file are mutually exclusive")
		}

		block, blockIdentity, err := s.resolveHex(call.RLP, call.RLPFile, "block RLP")
		if err != nil {
			return "", nil, nil, err
		}
		identity = append(identity, blockIdentity...)

		var payload any = block
		if call.BAL != "" || call.BALFile != "" {
			bal, balIdentity, resolveErr := s.resolveHex(call.BAL, call.BALFile, "block access list")
			if resolveErr != nil {
				return "", nil, nil, resolveErr
			}
			identity = append(identity, balIdentity...)
			payload = map[string]string{"block": block, "bal": bal}
		}

		waitPersistence := call.WaitForPersistence
		if waitPersistence == nil {
			waitPersistence = s.manifest.Defaults.WaitForPersistence
		}
		waitCaches := call.WaitForCaches
		if waitCaches == nil {
			waitCaches = s.manifest.Defaults.WaitForCaches
		}

		params = []any{payload}
		if waitPersistence != nil || waitCaches != nil {
			params = append(params, boolOrNil(waitPersistence))
		}
		if waitCaches != nil {
			params = append(params, *waitCaches)
		}
	}

	if method == "" {
		return "", nil, nil, fmt.Errorf("method is required when no block RLP is provided")
	}

	expectedStatus := call.ExpectedStatus
	if expectedStatus == "" && (method == "reth_newPayload" || method == "reth_forkchoiceUpdated") {
		expectedStatus = s.manifest.Defaults.ExpectedStatus
		if expectedStatus == "" {
			expectedStatus = "VALID"
		}
	}

	request := struct {
		JSONRPC string `json:"jsonrpc"`
		Method  string `json:"method"`
		Params  []any  `json:"params"`
		ID      int    `json:"id"`
	}{JSONRPC: "2.0", Method: method, Params: params, ID: id}

	encoded, err := json.Marshal(request)
	if err != nil {
		return "", nil, nil, fmt.Errorf("encoding JSON-RPC request: %w", err)
	}

	return string(encoded), &RequestMetadata{
		BlockNumber:             call.BlockNumber,
		BlockHash:               call.BlockHash,
		GasUsed:                 call.GasUsed,
		TransactionCount:        call.TransactionCount,
		ExpectedStatus:          expectedStatus,
		ValidationErrorContains: call.ValidationErrorContains,
		ExpectedRPCErrorCode:    call.ExpectedRPCErrorCode,
	}, identity, nil
}

func (s *tempoSuiteSource) resolveHex(inline, filename, field string) (string, []byte, error) {
	if inline != "" && filename != "" {
		return "", nil, fmt.Errorf("inline and file forms of %s are mutually exclusive", field)
	}

	value := []byte(strings.TrimSpace(inline))
	var identity []byte
	if filename != "" {
		path := s.resolvePath(filename)
		data, err := os.ReadFile(path)
		if err != nil {
			return "", nil, fmt.Errorf("reading %s file %q: %w", field, filename, err)
		}
		identity = appendIdentity(identity, filename, data)
		value = bytes.TrimSpace(data)
	}

	if len(value) == 0 {
		return "", nil, fmt.Errorf("%s is empty", field)
	}

	text := string(value)
	if strings.HasPrefix(text, "0x") {
		if _, err := hex.DecodeString(strings.TrimPrefix(text, "0x")); err != nil {
			return "", nil, fmt.Errorf("invalid hex %s: %w", field, err)
		}
		return text, identity, nil
	}

	if decoded, err := hex.DecodeString(text); err == nil && len(decoded) > 0 {
		return "0x" + text, identity, nil
	}

	return "0x" + hex.EncodeToString(value), identity, nil
}

func (s *tempoSuiteSource) Cleanup() error { return nil }

func (s *tempoSuiteSource) GetSourceInfo() (*SuiteSource, error) {
	if s.manifest == nil {
		return nil, fmt.Errorf("tempo suite source has not been prepared")
	}

	chain := s.manifest.Chain
	chain.Genesis = s.resolvePath(chain.Genesis)

	return &SuiteSource{Tempo: &TempoSourceInfo{
		Manifest:    s.manifestPath,
		Format:      s.manifest.Format,
		Name:        s.manifest.Name,
		Description: s.manifest.Description,
		Origin:      s.manifest.Origin,
		Chain:       chain,
		Metadata:    cloneStringMap(s.manifest.Metadata),
	}}, nil
}

func (s *tempoSuiteSource) GetGenesisPath(_ string) string {
	if s.manifest == nil || s.manifest.Chain.Genesis == "" {
		return ""
	}
	return s.resolvePath(s.manifest.Chain.Genesis)
}

func (s *tempoSuiteSource) resolvePath(path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(s.basePath, path)
}

type tempoStepProvider struct {
	lines    []string
	metadata []*RequestMetadata
}

var (
	_ StepProvider            = (*tempoStepProvider)(nil)
	_ RequestMetadataProvider = (*tempoStepProvider)(nil)
)

func (p *tempoStepProvider) Lines() []string {
	return append([]string(nil), p.lines...)
}

func (p *tempoStepProvider) Content() []byte {
	return []byte(strings.Join(p.lines, "\n") + "\n")
}

func (p *tempoStepProvider) RequestMetadata() []*RequestMetadata {
	return append([]*RequestMetadata(nil), p.metadata...)
}

func boolOrNil(value *bool) any {
	if value == nil {
		return nil
	}
	return *value
}

func appendIdentity(dst []byte, name string, content []byte) []byte {
	dst = append(dst, '\n')
	dst = append(dst, name...)
	dst = append(dst, 0)
	dst = append(dst, content...)
	return dst
}

func cloneStringMap(in map[string]string) map[string]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
