name: Check - PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:

concurrency:
  group: "title-checker-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  pr_title_checker:
    name: validate
    # Skip merge-queue PRs
    if: contains(github.ref_name, 'gh-readonly-queue/main/') != true
    runs-on: ubuntu-latest
    steps:
      - uses: tempoxyz/gh-actions/vendor/amannn/action-semantic-pull-request@b411ce7fe18d0775ae614ad5c4b873c768364979
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
