name: Check - Typos

permissions:
  contents: read

on: [pull_request]

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Spell Check Repo
      uses: tempoxyz/gh-actions/actions/typos@ab45d76f6e7420a094281a22aee1973ecc0754f8
